// Mocks generated by Mockito 5.4.6 from annotations
// in swim_tracker_mobile/test/features/training/data/time_standards_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:swim_tracker_mobile/src/features/training/data/time_standards_repository.dart'
    as _i2;
import 'package:swim_tracker_mobile/src/features/training/domain/time_standard.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TimeStandardsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeStandardsRepository extends _i1.Mock
    implements _i2.TimeStandardsRepository {
  MockTimeStandardsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TimeStandard>> getStandards({
    String? gender,
    String? ageGroup,
    String? course,
    String? event,
    _i4.StandardLevel? standardLevel,
    bool? motivationalOnly = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStandards,
          [],
          {
            #gender: gender,
            #ageGroup: ageGroup,
            #course: course,
            #event: event,
            #standardLevel: standardLevel,
            #motivationalOnly: motivationalOnly,
          },
        ),
        returnValue:
            _i3.Future<List<_i4.TimeStandard>>.value(<_i4.TimeStandard>[]),
      ) as _i3.Future<List<_i4.TimeStandard>>);

  @override
  _i3.Future<List<_i4.TimeStandard>> getStandardsForEvent({
    required String? gender,
    required String? ageGroup,
    required String? course,
    required String? event,
    bool? motivationalOnly = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStandardsForEvent,
          [],
          {
            #gender: gender,
            #ageGroup: ageGroup,
            #course: course,
            #event: event,
            #motivationalOnly: motivationalOnly,
          },
        ),
        returnValue:
            _i3.Future<List<_i4.TimeStandard>>.value(<_i4.TimeStandard>[]),
      ) as _i3.Future<List<_i4.TimeStandard>>);

  @override
  _i3.Future<_i4.TimeStandard?> getStandard({
    required String? gender,
    required String? ageGroup,
    required String? course,
    required String? event,
    required _i4.StandardLevel? standardLevel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStandard,
          [],
          {
            #gender: gender,
            #ageGroup: ageGroup,
            #course: course,
            #event: event,
            #standardLevel: standardLevel,
          },
        ),
        returnValue: _i3.Future<_i4.TimeStandard?>.value(),
      ) as _i3.Future<_i4.TimeStandard?>);

  @override
  _i3.Future<List<_i4.TimeStandard>> getStandardsByStrokeDistance({
    required String? gender,
    required String? ageGroup,
    required String? stroke,
    required int? distance,
    required String? course,
    bool? motivationalOnly = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStandardsByStrokeDistance,
          [],
          {
            #gender: gender,
            #ageGroup: ageGroup,
            #stroke: stroke,
            #distance: distance,
            #course: course,
            #motivationalOnly: motivationalOnly,
          },
        ),
        returnValue:
            _i3.Future<List<_i4.TimeStandard>>.value(<_i4.TimeStandard>[]),
      ) as _i3.Future<List<_i4.TimeStandard>>);

  @override
  _i3.Future<List<_i4.NationalTierStandard>> getNationalTierStandardsForEvent({
    required String? gender,
    required String? course,
    required String? event,
    required bool? use18AndUnder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNationalTierStandardsForEvent,
          [],
          {
            #gender: gender,
            #course: course,
            #event: event,
            #use18AndUnder: use18AndUnder,
          },
        ),
        returnValue: _i3.Future<List<_i4.NationalTierStandard>>.value(
            <_i4.NationalTierStandard>[]),
      ) as _i3.Future<List<_i4.NationalTierStandard>>);

  @override
  _i3.Future<Map<String, List<_i4.NationalTierStandard>>>
      getNationalTierStandardsByCourse({
    required String? gender,
    required String? course,
    required bool? use18AndUnder,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getNationalTierStandardsByCourse,
              [],
              {
                #gender: gender,
                #course: course,
                #use18AndUnder: use18AndUnder,
              },
            ),
            returnValue:
                _i3.Future<Map<String, List<_i4.NationalTierStandard>>>.value(
                    <String, List<_i4.NationalTierStandard>>{}),
          ) as _i3.Future<Map<String, List<_i4.NationalTierStandard>>>);
}
