#!/usr/bin/env python3
"""
Generate a Supabase migration that replaces time_standards table content
with data from time_standard.json (USA Swimming 2024-2028 motivational B–AAAA).
Run from repo root: python3 scripts/generate_time_standards_migration.py
Output: supabase/migrations/YYYYMMDD_sync_time_standards_from_json.sql
"""

import json
import re
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = REPO_ROOT / "time_standard.json"
MIGRATIONS_DIR = REPO_ROOT / "supabase" / "migrations"

EVENT_ABBREV = {
    "FR": ("Free", "Free"),
    "BK": ("Back", "Back"),
    "BR": ("Breast", "Breast"),
    "FL": ("Fly", "Fly"),
    "IM": ("IM", "IM"),
}


def parse_event(code: str) -> tuple[str, str, int]:
    """Return (event_name, stroke, distance). E.g. '50 FR' -> ('50 Free', 'Free', 50)."""
    parts = code.strip().split()
    if not parts:
        return ("", "", 0)
    distance = int(parts[0]) if parts[0].isdigit() else 0
    abbrev = parts[1].upper() if len(parts) > 1 else ""
    stroke = EVENT_ABBREV.get(abbrev, (abbrev, abbrev))[0]
    event_name = f"{distance} {stroke}"
    return (event_name, stroke, distance)


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def main() -> None:
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    groups = data.get("groups") or []

    rows: list[tuple[str, str, str, str, str, int, str, float]] = []
    for g in groups:
        age_group = g.get("age_group") or ""
        course = g.get("course") or ""
        gender = g.get("gender") or ""
        event_code = g.get("event") or ""
        event_name, stroke, distance = parse_event(event_code)
        if not stroke:
            continue
        for level in ["B", "BB", "A", "AA", "AAA", "AAAA"]:
            t = g.get(level)
            if t is None:
                continue
            try:
                time_seconds = float(t)
            except (TypeError, ValueError):
                continue
            rows.append((gender, age_group, course, event_name, stroke, distance, level, time_seconds))

    # Build SQL
    ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    migration_name = f"{ts}_sync_time_standards_from_json"
    out_path = MIGRATIONS_DIR / f"{migration_name}.sql"

    lines = [
        "-- Sync time_standards from time_standard.json (USA Swimming 2024-2028 motivational B–AAAA)",
        "-- Generated by scripts/generate_time_standards_migration.py",
        "",
        "-- Replace all existing rows with JSON data",
        "DELETE FROM public.time_standards;",
        "",
    ]

    # Batch INSERTs (Postgres supports multi-row VALUES); do chunks of 100 rows
    chunk_size = 100
    for i in range(0, len(rows), chunk_size):
        chunk = rows[i : i + chunk_size]
        values = []
        for (gender, age_group, course, event_name, stroke, distance, standard_level, time_seconds) in chunk:
            values.append(
                f"('{sql_escape(gender)}', '{sql_escape(age_group)}', '{sql_escape(course)}', "
                f"'{sql_escape(event_name)}', '{sql_escape(stroke)}', {distance}, "
                f"'{standard_level}', {time_seconds})"
            )
        lines.append(
            "INSERT INTO public.time_standards (gender, age_group, course, event, stroke, distance, standard_level, time_seconds) VALUES"
        )
        lines.append(",\n".join(values))
        lines.append(";")
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} rows to {out_path}")


if __name__ == "__main__":
    main()
